version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - /home/Minecraft/plugins:/plugins
    ports:
      - 25565:25565
    container_name: minecraft_server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      OPS: "LuisGamer02031"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "MOCHI SERVER"
      MEMORY: "4G"
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://cdn.vox-cdn.com/thumbor/8KxJUDwQsz5Qy-_HzZjtCTRR5PU=/0x164:1440x884/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/22310830/NmJgg.jpg"
      MOTD: "Welcome to the server!"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
