version: "3.4"

services:
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      FORGEVERSION: 36.2.34
      VERSION: 1.16.5
      OPS: "LuisGamer02031, "
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "Los Panas"
      MEMORY: 16G
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      ALLOW_CHEATS: "FALSE"
      WHITELIST: "LuisGamer02031"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MAX_PLAYERS: 50
      REMOVE_OLD_MODS: "FALSE"
      ICON: "https://picandocodigo.net/wp-content/uploads/2008/03/tux.3d.jpg"
      MOTD: "Welcome to Los Panas server!"
      GENERIC_PACK: "https://doc-0k-0g-docs.googleusercontent.com/docs/securesc/5lvmqil3r703lboacu42n854hui32mqc/qfoj2nrvnm9ssjluo8cefc468tnt7pd1/1679513775000/07943810283407467327/07943810283407467327/1tpcw0N31RHJa1fAqcf-wzaU8cjMjNxqK?e=download&ax=AB85Z1CliZ8LJ2DUqhSZgP9QfE8SuCpDoBPz5jkM0jDdpSsTmRNcf2VMwmbEJrN1XLox4CjoBJGLqoo1jE0KLDRlnkLmTpv1gXoW0q1gJKnKIt5HEDFLX9iO5fcBU9nWavBDIYkoExRzqWZFJcTj-mSt_VeWpCDBcBzE-IbjONG36Ts5yMclAPDCFILD7kcpyql58WH3n-F_qolml7QHTbtTUw5uvNvpy4CTm2O1pw-US6SMA6VBogJ88lyg4M_jocO9rtGGnW3R3kEN8NCMC6KV-FuXNZItfzbgCtQL4FU_Wi0d8xdHVJ77ObceZXWC_JbnnGxd8Yp_9bSYXrPPH0wmrEejLET0J9Y-W155PmxZhHWfvNepsJsPxQdn0tea8_aa301cecsEPPpB4XFMAHyXK42ZblMjOvkxExmNkjf9r2bGKtIunal_f3aeXTmgm7DhGD9_H0STsJZN1q9B_zGdbg_YH_IESXy3hdd0nPV3XmM2NacgsphwsQ5eaWUVs_Dz_GvLpg64MDMZoEb3rxmfQetL0TkTUTcqPPiDzeleD-YQqEZzflA1a1C5dF6CMGPVl0VzyuxusxWRiFrMkf01aO5CzwA6fB23mIH0H45RKst1VSQAaZEEpdIXpmRyrE2-4sldTJPqrMM-yK94OlXEKglbqc-uelZHxgk6FLCDnNhqbsXy9peX3N6wlsBGxgKCI4TMvrLHZAvV-xzVzzvmKDytycXaSGoNp2TsoBxpSYSupiRFEt9U0KywJP8QWPsbl66pUMbsXTfX5PvlHQ_DA8gVK8h_6t3QhHw0qaqlFKZXkPTzIH24ByoPkpAuCxlpElbmHsY7-Fn5S1VifBboTR3YUCiH8118_fBPVG_l-grvREA6NFdUsO8h5ywhYOcwstbkuPiGZ7DQH_f3iCOErZ_eJClK5LsEYt9mgg&uuid=669af954-568e-445f-a169-0bbb8966f419&authuser=0"
    volumes:
      - mc:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      # mount the same volume used by server, but read-only
      - mc:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro
volumes:
  mc: {}
