version: "3.4"

services:
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    container_name: modded_minecraft_server_panas
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      FORGEVERSION: 36.2.34
      VERSION: 1.16.5
      OPS: "LuisGamer02031"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "Los Panas"
      MEMORY: 8G
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_FLIGHT: "FALSE"
      ALLOW_CHEATS: "FALSE"
      WHITELIST: "LuisGamer02031"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MAX_PLAYERS: 50
      REMOVE_OLD_MODS: "FALSE"
      ICON: "https://cdn.vox-cdn.com/thumbor/8KxJUDwQsz5Qy-_HzZjtCTRR5PU=/0x164:1440x884/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/22310830/NmJgg.jpg"
      MOTD: "Welcome to Los Panas server!"
      GENERIC_PACK: "https://mediafiles.forgecdn.net/files/3949/63/Better+MC+Server+Pack+FORGE+1.16.5+v58.5.zip"
    volumes:
      - moddedminecraftserverdata:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    depends_on:
      - minecraft
    ports:
      - 25566:25565
    command: --mapping=https://minecraft.luishomeserver.com/=minecraft:25565
volumes:
  moddedminecraftserverdata:
    external: true
